"""Planning Orchestrator -- Strands GraphBuilder DAGs.

The pipeline is split across two graphs so that day-detail generation
can fan out to N parallel workers (one Strands node per day).

Skeleton graph (single-day count agnostic)::

    parse_input -> collect_context -> generate_skeleton -> validate_skeleton
                                              ^                    |
                                              |__ retry on FAIL ___|

Day details graph (built per request, N = skeleton.days)::

    prepare_day_prompts ─┬─▶ generate_day_1 ┐
                         ├─▶ generate_day_2 ├─▶ aggregate_days ─▶ validate_day_details
                         ├─▶ ...            │           ▲                  │
                         └─▶ generate_day_N ┘           └─── retry ────────┘
                                                       (only failed days re-run;
                                                        passed days no-op)
"""

from __future__ import annotations

import logging

from strands.multiagent.graph import GraphBuilder, GraphState
from strands.multiagent.base import Status

from src.orchestrator.nodes import (
    AggregateDaysNode,
    CollectContextNode,
    GenerateSingleDayNode,
    GenerateSkeletonNode,
    ParseInputNode,
    PrepareDayPromptsNode,
    SynthesizeNode,
    ValidateDayDetailsNode,
    ValidateSkeletonNode,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Conditional edge functions — skeleton graph
# ---------------------------------------------------------------------------

def _skeleton_needs_retry(state: GraphState) -> bool:
    result = state.results.get("validate_skeleton")
    if not result or result.status != Status.COMPLETED:
        return False
    text = str(result.result) if result.result else ""
    return "SKELETON_FAIL" in text


# ---------------------------------------------------------------------------
# Skeleton graph factory
# ---------------------------------------------------------------------------

def create_planning_graph() -> object:
    """Build the skeleton-stage graph (parse → collect → skeleton ↔ validate).

    Day details are generated by a separate per-request graph; the caller
    runs this graph first, then ``create_day_details_graph(N)`` second.
    """
    builder = GraphBuilder()

    builder.add_node(ParseInputNode(), "parse_input")
    builder.add_node(CollectContextNode(), "collect_context")
    builder.add_node(GenerateSkeletonNode(), "generate_skeleton")
    builder.add_node(ValidateSkeletonNode(), "validate_skeleton")

    builder.add_edge("parse_input", "collect_context")
    builder.add_edge("collect_context", "generate_skeleton")
    builder.add_edge("generate_skeleton", "validate_skeleton")
    builder.add_edge(
        "validate_skeleton", "generate_skeleton", condition=_skeleton_needs_retry
    )

    builder.set_entry_point("parse_input")
    builder.set_max_node_executions(12)
    builder.set_execution_timeout(300)
    builder.reset_on_revisit(True)

    graph = builder.build()
    logger.info("Skeleton planning graph built")
    return graph


# ---------------------------------------------------------------------------
# Day details graph — built per request with N day workers
# ---------------------------------------------------------------------------

def _days_need_retry(state: GraphState) -> bool:
    result = state.results.get("validate_day_details")
    if not result or result.status != Status.COMPLETED:
        return False
    text = str(result.result) if result.result else ""
    return "DAYS_FAIL" in text


def create_day_details_graph(day_count: int) -> object:
    """Build a fan-out / fan-in graph with one worker per day.

    Topology::

        prepare_day_prompts ──▶ generate_day_k (k=1..N) ──▶ aggregate_days
        validate_day_details ──▶ prepare_day_prompts   (on failure)

    Workers receive the same upstream completion (``prepare_day_prompts``)
    so they're scheduled in the same parallel batch by Strands.  On retry,
    the validator routes back to ``prepare_day_prompts`` which rebuilds
    only the failed days' prompts; workers whose prompt is absent no-op
    (so revisited workers are cheap), and the aggregator keeps using the
    previously-passed day outputs from invocation_state.
    """
    if day_count < 1:
        raise ValueError(f"day_count must be >= 1, got {day_count}")

    builder = GraphBuilder()

    builder.add_node(PrepareDayPromptsNode(), "prepare_day_prompts")
    builder.add_node(AggregateDaysNode(), "aggregate_days")
    builder.add_node(SynthesizeNode(), "synthesize")
    builder.add_node(ValidateDayDetailsNode(), "validate_day_details")

    worker_ids: list[str] = []
    for k in range(1, day_count + 1):
        node_id = f"generate_day_{k}"
        builder.add_node(GenerateSingleDayNode(day_num=k), node_id)
        worker_ids.append(node_id)

    # Fan-out: prepare → all workers
    for wid in worker_ids:
        builder.add_edge("prepare_day_prompts", wid)

    # Fan-in: all workers → aggregator → synthesize → validator.
    # Synthesize sits between aggregate and validate so it has the merged
    # PlanningOutput in front of it; the retry loop still routes back to
    # prepare_day_prompts on validation failure.
    for wid in worker_ids:
        builder.add_edge(wid, "aggregate_days")
    builder.add_edge("aggregate_days", "synthesize")
    builder.add_edge("synthesize", "validate_day_details")
    builder.add_edge(
        "validate_day_details", "prepare_day_prompts", condition=_days_need_retry
    )

    builder.set_entry_point("prepare_day_prompts")
    # Worst case: 3 retries × (1 prepare + N workers + 1 aggregate + 1 validate)
    # plus the initial pass. Pad for safety.
    builder.set_max_node_executions((day_count + 3) * 4 + 4)
    builder.set_execution_timeout(600)
    builder.reset_on_revisit(True)

    graph = builder.build()
    logger.info(
        "Day details graph built with %d parallel workers", day_count
    )
    return graph
