default_agent: ota_travel_agent
agents:
  ota_travel_agent:
    name: ota_travel_agent
    language: python
    node_version: '20'
    entrypoint: /home/ec2-user/project/travel-md/agent/src/agentcore_app.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /home/ec2-user/project/travel-md/agent
    aws:
      execution_role: arn:aws:iam::REDACTED_ACCOUNT_ID:role/REDACTED_EXECUTION_ROLE_SUFFIX
      execution_role_auto_create: false
      account: 'REDACTED_ACCOUNT_ID'
      region: ap-northeast-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-REDACTED_ACCOUNT_ID-ap-northeast-2
      s3_auto_create: false
      network_configuration:
        network_mode: VPC
        network_mode_config:
          security_groups:
          - sg-07885136908f7ce10
          subnets:
          - subnet-08509ad1a54a39060
          - subnet-04d7fd52f42271a13
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: REDACTED_TRAVEL_AGENT_ID
      agent_arn: arn:aws:bedrock-agentcore:ap-northeast-2:REDACTED_ACCOUNT_ID:runtime/REDACTED_TRAVEL_AGENT_ID
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
